name: Deploy Docs and Storybook

on:
  workflow_dispatch:
  push:
    branches: [ master, latest ]

jobs:
  deploy-docs-n-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        persist-credentials: false
    
    - name: Info
      run: echo "Running on branch $(basename ${{ github.ref }})"
    
    - name: Create build dir
      run: mkdir docs_out    
    
    - name: Generate storybook
      run:  npx build-storybook -c .storybook -o docs_out/storybook/$(basename ${{ github.ref }})
    
    - name: Build documentation # only if this was triggered from master
      if: github.ref == 'refs/heads/master' 
      # TODO: replace these with `npm docs` and `npm postdocs` once you are sure everything works
      run: |
        npx typedoc --out docs_out src
        npx copyfiles images/* docs_out && copyfiles .nojekyll docs_out
        
    - name: Publish GH pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  # The branch the action should deploy to.
        FOLDER: docs_out  # The folder the action should deploy.
